version: "3.8"
services:
    app:
        build:
            args:
                user: edgar
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: pengajuan-prestasi
        container_name: pengajuan-prestasi-app
        restart: unless-stopped
        depends_on:
            - db
        #volumes:
        #    - ./:/var/www
        networks:
            - pengajuan-prestasi
    db:
        image: mysql:8.0
        container_name: pengajuan-prestasi-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - pengajuan-prestasi
    nginx:
        image: nginx:alpine
        container_name: pengajuan-prestasi-nginx-app
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - pengajuan-prestasi

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        restart: always
        ports:
            - "8001:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - pengajuan-prestasi
networks:
    pengajuan-prestasi:
      driver: bridge
